### ISSUE TITLE
Q: can it work with scss preprocess?

### ISSUE THREAD

**Issue by Valexr** [winston0410/glory-svelte-preprocess#2]
```svelte
<style lang="scss">
```

**Comment by winston0410** [comment]
I think so, but you have to place this preprocessor after scss preprocessor, as this one only handles vanilla CSS.

**Comment by Valexr** [comment]
Ok🤓will try it

**Comment by winston0410** [comment]
@Valexr Do let me know if there is any bug!:)

**Comment by Valexr** [comment]
Yep, I have a bug with `<style lang=scss>` with esbuild-svelte plugin:

![Screenshot 2021-08-20 at 14 51 05](https://user-images.githubusercontent.com/5656366/130229018-b7bd972b-ab12-4e6b-b48e-c252143b777e.jpg)

testing [repo](https://github.com/Valexr/svelte-glory)

**Comment by winston0410** [comment]
@Valexr thank you for the testing repo! I will use it and see how can I fix that.

**Comment by Valexr** [comment]
But I'm haven't testings with other bundlers... like rollup or webpack

**Comment by winston0410** [comment]
@Valexr It will work if you use a wrapper like this: https://github.com/winston0410/svelte-glory/commit/f8744a3ad51ca6e271e36bf4171336ede75fc4b3

As explained here: https://www.npmjs.com/package/svelte-as-markup-preprocessor

Btw I would be great if you can help out making a benchmark repo:)

**Comment by Valexr** [comment]
preprocess is not defined 🤷🏻‍♂️

**Comment by winston0410** [comment]
Sorry it should be this: https://github.com/winston0410/svelte-glory/commit/4715e88b77c6b82ad0e9be91189644e6335f21ad

Good catch!

**Comment by Valexr** [comment]
It's building now, but missing inherited class in element `<h1 class>`

**Comment by winston0410** [comment]
@Valexr good catch, let me check it again

**Comment by winston0410** [comment]
@Valexr It was the issue with descendant combinators. Fixed in https://github.com/winston0410/glory-svelte-preprocess/commit/227a0bb4fe6c7b1fd33e4da9d95f6af16edc8955

**Comment by Valexr** [comment]
Sorry, but in 0.1.9 one more error

![Screenshot 2021-08-24 at 06 45 31](https://user-images.githubusercontent.com/5656366/130552706-a82352ef-5e02-4479-a782-76bf05da20d2.jpg)

🤷🏻‍♂️

**Comment by Valexr** [comment]
v 0.2.0 still error

**Comment by winston0410** [comment]
I have just refactored to support more selectors, and I guess I will take a few more day to fix it and make it usable again.

**Comment by Valexr** [comment]
It's ok🤓just trying help you with SASS preprocessing testing, if you need this exactly

**Comment by winston0410** [comment]
Yes please do! Any testing is helpful:)

**Comment by winston0410** [comment]
@Valexr I think I have fixed all previously mentioned issue in `0.2.2`, maybe you can give it a try now.

https://github.com/winston0410/svelte-glory/commit/a847cf981cbbbac5222f9c1ec6b91fdf16a49c7f

**Comment by Valexr** [comment]
Yep👍🏻working 👌🏻

**Comment by Valexr** [comment]
But in more complicated project with CSS & SCSS together:

```sv
<style lang="scss">
  @import "base.scss"
</style>

// or

<style src="variables.css"></style>
```

I have a bug
![Screenshot 2021-08-25 at 15 34 20](https://user-images.githubusercontent.com/5656366/130791275-0f395872-5d3d-4432-baea-d2a328a3334c.jpg)

while  don't understand with what...

**Comment by Valexr** [comment]
Update testing [repo](https://github.com/Valexr/svelte-glory) with global attribute no bugs but broken styles

**Comment by winston0410** [comment]
@Valexr For the error message,  the issue is in esbuild itself, which I guess it doesn't pass the log back from worker thread to the thread used in Node. I will look at the error again tomorrow.

**Comment by winston0410** [comment]
@Valexr seems like it is working now, can you give it a try?
https://github.com/winston0410/svelte-glory

Btw is there any documentation for using `src` in `<style>` in svelte? I cannot find it.

**Comment by Valexr** [comment]
Yep, it's working, but add whitespaces

with glory
<img src=https://user-images.githubusercontent.com/5656366/131568643-7de64aaf-9cbc-4599-8ff0-f80d77cb292c.jpg width=300 />

without
<img src=https://user-images.githubusercontent.com/5656366/131568664-aa7a37b9-2674-4e73-8d54-b92770308c29.jpg width=300 />

**Comment by winston0410** [comment]
@Valexr Can you find out what class is added/missing there between two version?

**Comment by Valexr** [comment]
Missing @media query

![Screenshot 2021-09-01 at 09 56 19](https://user-images.githubusercontent.com/5656366/131626116-3f388656-117e-4868-a5ee-4ca977d02972.jpg)

**Comment by winston0410** [comment]
Right it is media query, and I have fixed it this morning.Maybe you can give it a try again now? (install from github instead of npmm it is breaking a lot right so I guess I wont publish on npm untill bug free)

**Comment by Valexr** [comment]
Ok. What true link from GitHub?
